### ISSUE TITLE
Error on start up

### ISSUE THREAD

**Issue by Raideno6** [sultim-t/xash-rt#36] opened 2023-02-24 02:51 UTC
Im new to this, and when I go to launch xash3d.exe I get this error
![image](https://user-images.githubusercontent.com/116860736/221080074-28819837-365c-40f6-a2e1-6e7a7cabf1b0.png)

**Comment by Stann0xus** [comment] 2023-02-24 03:46
![image](https://user-images.githubusercontent.com/125307936/221087069-766f8794-1b08-47bc-a658-4300a776171a.png)
As well, Im on RTX2060S

**Comment by SvyatoyDanil** [comment] 2023-02-24 08:08
> ![image](https://user-images.githubusercontent.com/125307936/221087069-766f8794-1b08-47bc-a658-4300a776171a.png) As well, Im on RTX2060S

I have the same

**Comment by boofiboi** [comment] 2023-02-24 14:32
Same here, running an RX 5500XT with the RADV RT emulation. Works fine on q2rtx, not here. Just keeps giving me this error.
![image](https://user-images.githubusercontent.com/79476279/221204018-cab758d2-8177-425b-8c78-1fddaeafc5cd.png)

**Comment by sultim-t** [comment] 2023-02-24 18:41
Duplicate of #2

**Closed as completed by sultim-t** 2023-02-24 18:41 UTC

**Comment by MixedVictor** [comment] 2023-02-24 20:15
> Same here, running an RX 5500XT with the RADV RT emulation. Works fine on q2rtx, not here. Just keeps giving me this error. ![image](https://user-images.githubusercontent.com/79476279/221204018-cab758d2-8177-425b-8c78-1fddaeafc5cd.png)

Try using Winetricks to download vcrun2019 and see if it works
