### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by 7Works** [sultim-t/xash-rt#13] opened 2023-02-23 05:51 UTC
I've installed it exactly like it says in instruction and it gives me the same error every time I try to launch it:
![image](https://user-images.githubusercontent.com/126140383/220830234-d9338a2d-f339-421f-a86e-e447ed07df86.png)
![image](https://user-images.githubusercontent.com/126140383/220830251-e64358b7-02e2-447a-b64f-846f4af749d2.png)
Is there a way to fix this?
I have NVIDIA GTX 1660, if it helps (and maybe this GPU won't be suitable to launch this, but I didn't see any system requirements, so I've just wanted to give it a try)

**Comment by sultim-t** [comment] 2023-02-23 07:09
Duplicate of #2

**Closed as completed by sultim-t** 2023-02-23 07:09 UTC
