### ISSUE TITLE
Crash on start-up

### ISSUE THREAD

**Issue by vomika7** [sultim-t/xash-rt#47] opened 2023-02-24 17:06 UTC
Nvidia 1070ti / brand new install of half-life

![image](https://user-images.githubusercontent.com/58232110/221242349-50de981e-f393-4c12-ae8e-fe58db4633ee.png)

**Comment by sultim-t** [comment] 2023-02-24 18:39
Duplicate of #2

**Closed as completed by sultim-t** 2023-02-24 18:39 UTC
